truncate "public"."file_tipos" RESTART IDENTITY;
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (1,'Análisis de riesgos');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (2,'Plan reduccion de riesgos');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (3,'Plan de contingencias');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (4,'Plan de continuidad de operaciones');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (5,'Carta de Corresponsabilidad del tercer acreditado ');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (6,'Carta de Responsabilidad expedida por el obligado');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (7,'Copia de Póliza Seguro');
--INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (8,'Evaluacion de Riesgo-Vulnerabilidad del Establecimiento');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (9,'Dictamen de Seguridad Estructural firmado por un D.R.O. debidamente acreditado y con registro ante la Secretaria de Desarrollo Urbano y Vivienda');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (10,'Oficio de no modificación o cambios estructurales, firmado por el administrador o poseedor del inmueble');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (11,'Dictamen de instalación de gas LP o natural firmado por una unidad verificadora avalada y con registro en la SENER');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (12,'Prueba de presión en equipo hidrantes, firmada por la empresa que realice los trabajos.');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (13,'Carta bajo protesta de decir verdad indicando las características del Equipo de Alerta, Prevención y Combate de Incendios, firmada por el administrador o poseedor del inmueble');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (14,'Carta bajo protesta de decir verdad indicando las características del Equipo de Primeros Auxilios firmada por el administrador o poseedor del inmueble');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (15,'Carta bajo protesta de decir verdad indicando las características del Equipo de Alerta Sísmica firmada por el administrador o poseedor del inmueble');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (16,'Organigrama del Comité Interno de Protección Civil');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (17,'Calendario de Capacitación');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (18,'Bitácoras del Programa de Capacitación');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (19,'Cronograma y bitácora de simulacros');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (20,'Organigrama del Comité Interno de Protección Civil (Atención de emergencias)');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (21,'Calendario de Capacitación (Atención de emergencias)');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (22,'Bitácoras del Programa de Capacitación (Atención de emergencias)');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (23,'Cronograma y bitácora de simulacros (Atención de emergencias)');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (24,'Croquis de la ubicación del inmueble y sus alrededores');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (25,'Croquis general del centro de trabajo');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (26,'Croquis de distribución de áreas');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (27,'Croquis de ubicación de equipamiento a Grupos de Atención Especial');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (28,'Croquis de ubicación de botiquines de Primeros Auxilios');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (29,'Croquis de distribución de brigadistas');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (30,'Croquis de ubicación de equipos de alerta, prevención y combate de incendios');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (31,'Croquis de localización de riesgo eléctrico');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (32,'Croquis indicando la trayectoria de la Ruta de Evacuación');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (33,'Croquis de salidas y escaleras de emergencia');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (34,'Croquis de ubicación del sistema de alerta sísmica');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (35,'Croquis de ubicación de las Zonas de Menor Riesgo');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (36,'Croquis de la ubicación de las Zonas de Riesgo');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (37,'Acta Constitutiva de la integración del Comité interno actualizado');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (38,'Programa Anual de Mantenimiento a las Instalaciones (Eléctricas, gas L.P, sistemas fjos, etc.)');
INSERT INTO "public"."file_tipos" (id,descripcion) VALUES (39,'Carta responsiva de extintores');
