truncate "public"."figuras" RESTART IDENTITY;
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos,esobligatorio) VALUES ('Responsable de piso o de edificio','Coordinación general',true,false,true);
--INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos) VALUES ('Suplente del coordinador general','Coordinación general',true,false);
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos) VALUES ('Jefe de edificio','Jefaturas',true,false);
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos) VALUES ('Jefe de seguridad','Jefaturas',true,false);
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos) VALUES ('Jefe de mantenimiento','Jefaturas',true,false);
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos,esobligatorio) VALUES ('Jefe de piso','Jefaturas',true,true,true);
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos) VALUES ('Jefe de brigada de primeros auxilios','Jefaturas',true,false);
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos) VALUES ('Jefe de brigada de evacuación','Jefaturas',true,false);
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos) VALUES ('Jefe de brigada de prevención, combate y extinción de incendios','Jefaturas',true,false);
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos) VALUES ('Jefe de brigada de comunicación','Jefaturas',true,false);
INSERT INTO "public"."figuras" (descripcion,agrupacion,unapersona,enpisos) VALUES ('Jefe de brigada del grupo de apoyo especial','Jefaturas',true,false);
INSERT INTO "public"."figuras" (agrupacion,descripcion,unapersona,enpisos) VALUES ('Brigadista','Brigadistas primeros auxilios',false,false);
INSERT INTO "public"."figuras" (agrupacion,descripcion,unapersona,enpisos) VALUES ('Brigadista','Brigadistas de evacuación',false,false);
INSERT INTO "public"."figuras" (agrupacion,descripcion,unapersona,enpisos) VALUES ('Brigadista','Brigadistas de prevención, combate y extinción de incendios.',false,false);
INSERT INTO "public"."figuras" (agrupacion,descripcion,unapersona,enpisos) VALUES ('Brigadista','Brigadistas de comunicación',false,false);
INSERT INTO "public"."figuras" (agrupacion,descripcion,unapersona,enpisos) VALUES ('Brigadista','Brigadistas de apoyo especial (GAE)',false,false);
INSERT INTO "public"."figuras" (agrupacion,descripcion,unapersona,enpisos) VALUES ('Brigadista','Brigadistas de grupo de apoyo psicosocial',false,false);
INSERT INTO "public"."figuras" (agrupacion,descripcion,unapersona,enpisos) VALUES ('Brigadista','Brigadistas de multifuncional',false,false);
