truncate "public"."juzgados" RESTART IDENTITY;
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (1,'AOB - 1','Escuadrón 201 esq. Batallón de San Patricio s/n, Col. Cristo Rey','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (1,'AOB - 2','Camino Real de Toluca s/n entre Paralela 2 y 3, Col. José María Pino Suárez, C.P. 01140','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (1,'AOB - 3','Tlaxcala y Av. México, Col. Progreso Tizapan','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (1,'AOB - 4','Tlaxcala y Av. México, Col. Progreso Tizapan','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (2,'AZC - 1','Av. De las Culturas y Eje 5 Norte, San Martín Xochinahuac, Unidad Hab. El Rosario, C.P. 02100','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (2,'AZC - 2','Av. 22 de Febrero y Castilla Oriente, Colonia Del Maestro (Sector Clavería) C.P. 02100','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (2,'AZC - 3','Av. 22 de Febrero y Castilla Oriente, Colonia Del Maestro (Sector Clavería) C.P. 02101','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (2,'AZC - 4','Av. 22 de Febrero y Castilla Oriente, Colonia Del Maestro (Sector Clavería) C.P. 02102','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (2,'Centro de Justicia para Mujeres Azcapotzalco','Av. San Pablo 396, Col San Martín Xochinahuac','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (3,'BJU - 1','Av. División del Norte esq. Eje 7 Sur Municipio Libre, Col. Santa Cruz Atoyac','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (3,'BJU - 2','Obrero Mundial 295 esq. Av. Cuauhtémoc,  Col. Narvarte.','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (3,'BJU - 3','Obrero Mundial 295 esq. Av. Cuauhtémoc,  Col. Narvarte.','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (3,'BJU - 4','Obrero Mundial 295 esq. Av. Cuauhtémoc,  Col. Narvarte.','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (3,'BJU - 5','Bretaña No. 6 y Orinoco, Colonia Zacahuixco (Portales), C.P. 03300','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (4,'COY - 1','Teculiapan y Zompantitlan, Col. Romero de Terreros, C.P. 04210','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (4,'COY - 3','Apaches y Eje 3 Oriente Cafetales s/n, Col. San Francisco Culhuacán','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (4,'COY - 4','Tepalcatzin y Meconetzin, Colonia Ajusco Zona Pedregales','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (4,'COY - 2','Tepalcatzin y Meconetzin, Colonia Ajusco Zona Pedregales','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (4,'COY - 5','Canal Nacional  y Laura Méndez Cuenca, Colonia CTM Culhuacán Cheroquis','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'CUH - 1','Lerdo 322, Colonia San Simón Tolnahúacan ','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'CUH - 2','Aldama y Mina (Edificio Delegacional) Colonia Buenavista C.P. 06300','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'CUH - 3','Paseo de la Reforma No. 705, Colonia Morelos','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'Centro de Legalidad y Justicia CUH-04','Paraguay No. 37, Col Centro','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'CUH -5','Calle Santa María la Rivera No. 35, Colonia Sta. María la Rivera','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'CUH -6','SIN INSTALACIONES','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'CUH -7','SIN INSTALACIONES','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'Centro Intregral de Justicia Metro Guerrero','Zarco y Mosqueta, Col. Guerrero','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'CUH - 8','Plaza Pino Suarez, Colonia Centro, C.P. 06090','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (6,'CUJ - 1','Castillo Ledón y Cerrada Ramírez, Colonia Cuajimalpa de Morelos, C.P. 05000','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (6,'CUJ - 2','Castillo Ledón y Cerrada Ramírez, Colonia Cuajimalpa de Morelos, C.P. 05001','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (7,'GAM - 1','Emiliano Zapata y Guadalupe Victoria, Colonia Cuauhtepec Barrio Bajo, C.P. 07200','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (7,'GAM - 2','Av. Congreso de la Unión 625 A, Col. Granjas Modernas.','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (7,'GAM - 3','Cda. Sur de los 100 metros s/n, Entre Vallejo y Eje Central, Colonia Vallejo','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (7,'GAM - 4','Vicente Villada y 5 de Febrero, Colonia Aragón la Villa, C.P. 07050','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (7,'GAM - 5','Av. 416 esq. Loreto Fabela, Col. San Juan de Aragón (Al costado sur del Deportivo Los Galeana)','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (7,'GAM - 6','Malitzin No. 146 y 148 esq. Francisco Novo, Colonia Aragón la Villa','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (7,'GAM - 7','Av. 661 ,entre Av. 606 y Av. 604, Col. San Juan de Aragón 6a. Sección','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (7,'GAM - 8','Av. 661 ,entre Av. 606 y Av. 604, Col. San Juan de Aragón 6a. Sección','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (8,'IZC - 1','Av. Congreso de la Unión casi esq. Con Av. Coyuya, Col. Santa Anita (Paradero Metro Santa Anita)','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (8,'IZC - 2','Sur 157 y Calle T, Colonia Gabriel Ramos Millán, C.P. 08000','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (8,'IZC - 3','Sur 157 y Calle T, Colonia Gabriel Ramos Millán, C.P. 08001','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'IZP - 1','Ermita Iztapalapa esq. Tercer anillo de Circunvalación, Barrio Santa Bárbara.','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'IZP - 2','Ermita Iztapalapa esq. Tercer anillo de Circunvalación, Barrio Santa Bárbara.','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'IZP - 3','Militares S/N, Col. Area Federal, Interior de la Central de Abastos','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'IZP - 4','Av. 5 de Mayo y Callejón Victoria, Barrio San Lucas, C.P. 09000','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'IZP - 5','Campaña del Ébano No. 20, entre Revolución Social y Combate de Celaya, U.H. Vicente Guerrero, C.P. 09200','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'IZP - 6','Calle Tres y Telecomunicaciones, Colonia Tepalcates (Cabeza de Juárez)','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'IZP - 7','Calzada San Lorenzo Tezonco No. 310, Colonia San Nicolás Tolentino','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'IZP - 8','Av. Zacatlan Mz. 4 Lt. 20, área federal Panteón San Lorenzo Tezonco.','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'IZP - 9','Calzada Ermita Iztapalapa esq. Zacatepetl, Col. Santa Martha Acatitla','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (9,'Centro de Justicia para Mujeres Iztapalapa','Calle 20 de Noviembre, Mz. 227, Lt. 29, Ixtlahuacan, C.P. 09690','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (10,'MAC - 1 T1','Av. San Jerónimo No. 2625, esquina Soledad, Colonia Lomas de San Bernabé (El Oasis)','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (10,'MAC - 2 T1','Cruz Verde No. 4, Colonia San Nicólas (Sector de Policía)','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (11,'MIH - 1','Calzada México Tacuba y  Mar Arabigo, Colonia Tacuba, C.P. 11410','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (11,'MIH - 2','SOLICITAR ESPACIO A LA PROCURADURIA ','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (11,'MIH - 3','Parque Lira No.  94 Esquina Vicente Eguía, Colonia Daniel Garza, C.P. 11860','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (11,'MIH - 4','Parque Lira No.  94 Esquina Vicente Eguía, Colonia Daniel Garza, C.P. 11861','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (11,'MIH - 5','Parque Lira No.  94 Esquina Vicente Eguía, Colonia Daniel Garza, C.P. 11862','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (12,'MIL - 1 T2','Av. Jalisco casi esquina con Av. México, Barrio San Mateo, Villa Milpa Alta, C.P. 12000','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (12,'MIL - 2 T2','Prolongación Ignacio Zaragoza y 5 de Mayo, San Antonio Tecomitl ','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (13,'TLH - 1 T2','Av. Canal de Chalco S/N, entre Piraña y Langosta, Colonia Del Mar, C.P. 13270','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (13,'TLH - 2 T2','Nicolás Bravo s/n Av. Tlahuac, Barrio La Asunción,  C.P. 13040','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (14,'TLP - 1','Carretera Picacho Ajusco Km. 4.5 Col Ampliacion Miguel Hidalgo  ','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (14,'TLP - 2','Matamoros y Jojutla, Colonia La Joya','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (14,'TLP - 3','Matamoros y Jojutla, Colonia La Joya','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (14,'TLP - 4','Canal Nacional esq. Anillo Periférico Sur (Aun costado de la U.H. INFONAVIT Dr. Ignacio Chávez)','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (15,'VCA - 1','San Ciprián No. 63 y General Anaya, Colonia Centro (Mercado San Ciprián)','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (15,'VCA - 2','Boulevard Puerto Aereo y Norte 13, Colonia Moctezuma 2a. Sección','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (15,'VCA - 3','Fray Servando T. de Mier y Fco. del Paso y Troncoso, Col. Jardin Balbuena (Aun costado del Edificio Delegacional), C.P. 01080','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (15,'VCA - 4','Calle Circunvalación y Prolongación Río Churubusco, Col. El Caracol','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (15,'VCA - 5','Calle Circunvalación y Prolongación Río Churubusco, Col. El Caracol','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (16,'XOC - 1','Circuito Martínez de Castro s/n, Pueblo San Mateo Xalpa, C.P. 16800 (Edificio de los Juzgados Penales del Fuero Común del TSJDF)','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (16,'XOC - 2','Cuitlahuac y Gladiolas, Barrio San Pedro Xochimilco, C.P. 16090','24x48','09:00 - 09:00');
insert into juzgados (idalcaldia,juzgado,direccion,turno,horario) values (5,'DEJC','Xoco+C17:D79ngo #131 1er Piso, Col. Tránsito, Alcaldía Cuauhtemoc, C.P. 06000','24x48','09:00 - 09:00');

