--select * from users 
--where email='jlvdantry@hotmail.com';
--select * from perfiles_users where idusuario=20;
--select * from perfiles;
--delete from users where email='jlvdantry@hotmail.com';
--update boletas set estatus=0 where boleta_remision='SDGBFGNDDFG';
--select * from boletas where boleta_remision='SDGBFGNDDFG';
--select * from infractores where idboleta=(select id from boletas where boleta_remision='SDGBFGNDDFG');
select * from infracciones
--select users.*,case when activo=0 then 'Pendiente' when activo=1 then 'Aceptado' when activo=2 then 'Rechazado' when activo=3 then 'Eliminado' else 'Desconocido' end desactivo , (trim(coalesce(nombres,'')) || ' ' || trim(coalesce(ape_pat,'')) || ' ' || trim(coalesce(ape_mat,''))) nombrecompleto ,(select descripcion from perfiles pe where pe.id in (select idperfil from perfiles_users where idusuario=users.id) order by id desc limit 1) desperfil ,(select id from perfiles pe where pe.id in (select idperfil from perfiles_users where idusuario=users.id) order by id desc limit 1) idperfil ,(select juzgado from juzgados where id = users.idjuzgado) desjuzgado,(select direccion from juzgados where id = users.idjuzgado) dirjuzgado from users  left join perfiles_users pu on  idusuario=users.id  where pu.idperfil=1 
--and idjuzgado=
